<?php
/**
 * @var $block Wise\BuyExample\Block\AddExampleToCart
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add Example to Cart (' . $block->getPriceMessage($_product) . ')'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button type="button"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-example-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif;
?>