<?php
/**
 * @var $block Wise\BuyExample\Block\AddExampleToCart
 */

$_product = $block->getProduct();
/**
 * @var $helper Wise\BuyExample\Helper\Data
 */
$helper = $this->helper('Wise\BuyExample\Helper\Data');
$isEnabled = $helper->isEnabled();
?>
<?php if ($isEnabled): ?>
    <?php $buttonTitle = __('Add Example to Cart (' . $block->getPriceMessage($_product) . ')'); ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="box-example-tocart">
            <div class="fieldset">
                <div class="actions">
                    <button type="submit"
                            title="<?= /* @escapeNotVerified */
                            $buttonTitle ?>"
                            class="action primary example-tocart"
                            id="product-addtocart-example-button">
                        <span><?= /* @escapeNotVerified */
                            $buttonTitle ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>


<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Wise_BuyExample/add-wise-example-to-cart": {}
        }
    }
</script>